apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: notebookjobs.microsoft.k8s.io
spec:
  group: microsoft.k8s.io
  names:
    kind: NotebookJob
    plural: notebookjobs
  scope: Namespaced
  additionalPrinterColumns:
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: RunID
    type: integer
    description: Run ID in DataBricks
    JSONPath: .spec.notebookTask.runID
  - name: State
    type: string
    JSONPath: .status.stateMessage
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterSpec:
              properties:
                nodeTypeId:
                  type: string
                numWorkers:
                  format: int64
                  type: integer
                sparkVersion:
                  type: string
              type: object
            notebookAdditionalLibraries:
              items:
                properties:
                  properties:
                    type: object
                  type:
                    type: string
                required:
                - type
                - properties
                type: object
              type: array
            notebookSpec:
              type: object
            notebookSpecSecrets:
              items:
                properties:
                  mapping:
                    items:
                      properties:
                        outputKey:
                          type: string
                        secretKey:
                          type: string
                      required:
                      - secretKey
                      - outputKey
                      type: object
                    type: array
                  secretName:
                    type: string
                required:
                - secretName
                - mapping
                type: object
              type: array
            notebookTask:
              properties:
                notebookPath:
                  type: string
                runID:
                  format: int64
                  type: integer
              type: object
            timeoutSeconds:
              format: int64
              type: integer
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
