
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - dbfsblocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - dbfsblocks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - databricks.microsoft.com
  resources:
  - dclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - dclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - databricks.microsoft.com
  resources:
  - djobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - djobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - databricks.microsoft.com
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - runs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - runs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - databricks.microsoft.com
  resources:
  - secretscopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - secretscopes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - databricks.microsoft.com
  resources:
  - workspaceitems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databricks.microsoft.com
  resources:
  - workspaceitems/status
  verbs:
  - get
  - patch
  - update
